import type { AgentAdapter, AdapterName, GeneratedFile, ProjectContext, WorkspaceManifest } from "../schemas.js";

const managedHeader = "<!-- Generated by agent-workspace. Edit .agent-workspace/ instead. -->";

function workspaceGuide(tool: string, project: ProjectContext): string {
  return `${managedHeader}\n# ${tool} repository instructions\n\nUse the canonical workspace in \`.agent-workspace/\` before making changes.\n\n- Read \`.agent-workspace/context/project.md\` for detected facts and evidence.\n- Select the most relevant role from \`.agent-workspace/agents/\`.\n- Follow the matching reproducible workflow in \`.agent-workspace/skills/\`.\n- Treat detected facts as evidence, inferred conventions as provisional, and recommendations as editable.\n- Use repository commands documented in \`.agent-workspace/context/project.md\`.\n- Keep changes scoped and report validation performed.\n\nProject: ${project.name}\n`;
}

function cursorGuide(project: ProjectContext): string {
  return `---\ndescription: Repository-aware engineering workflow generated by agent-workspace\nalwaysApply: true\n---\n\n${workspaceGuide("Cursor", project).replace(`${managedHeader}\n`, "")}`;
}

class MarkdownAdapter implements AgentAdapter {
  constructor(public readonly name: AdapterName, public readonly displayName: string, private readonly filePath: string) {}
  async detect(): Promise<boolean> { return false; }
  async generate(_workspace: WorkspaceManifest, project: ProjectContext): Promise<GeneratedFile[]> {
    return [{ path: this.filePath, content: workspaceGuide(this.displayName, project), managed: true }];
  }
}

export const adapters: Record<AdapterName, AgentAdapter> = {
  codex: new MarkdownAdapter("codex", "OpenAI Codex", "AGENTS.md"),
  opencode: new MarkdownAdapter("opencode", "OpenCode", "AGENTS.md"),
  claude: new MarkdownAdapter("claude", "Claude Code", "CLAUDE.md"),
  copilot: new MarkdownAdapter("copilot", "GitHub Copilot", ".github/copilot-instructions.md"),
  gemini: new MarkdownAdapter("gemini", "Gemini CLI", "GEMINI.md"),
  cursor: {
    name: "cursor",
    displayName: "Cursor",
    async detect() { return false; },
    async generate(_workspace, project) { return [{ path: ".cursor/rules/agent-workspace.mdc", content: cursorGuide(project), managed: true }]; },
  },
};

export function uniqueAdapterFiles(files: GeneratedFile[]): GeneratedFile[] {
  const seen = new Set<string>();
  return files.filter((file) => {
    if (seen.has(file.path)) return false;
    seen.add(file.path);
    return true;
  });
}
