import { access } from "node:fs/promises";
import path from "node:path";
import type { AgentAdapter, AdapterName, GeneratedFile, ProjectContext, WorkspaceManifest } from "../schemas.js";

const managedHeader = "<!-- Generated by agent-workspace. Edit .agent-workspace/ instead. -->";
const markers: Record<AdapterName, string[]> = {
  codex: [".codex", "AGENTS.md"],
  claude: [".claude", "CLAUDE.md"],
  cursor: [".cursor", ".cursorrules"],
  copilot: [".github/copilot-instructions.md", ".github/instructions"],
  gemini: [".gemini", "GEMINI.md"],
  opencode: [".opencode", "opencode.json", "opencode.jsonc"],
};

export const adapterOutputPaths: Record<AdapterName, string> = {
  codex: "AGENTS.md",
  claude: "CLAUDE.md",
  cursor: ".cursor/rules/agent-workspace.mdc",
  copilot: ".github/copilot-instructions.md",
  gemini: "GEMINI.md",
  opencode: "AGENTS.md",
};

async function markerExists(root: string, relative: string): Promise<boolean> {
  try { await access(path.join(root, relative)); return true; } catch { return false; }
}

async function detectMarkers(name: AdapterName, project: ProjectContext): Promise<boolean> {
  return (await Promise.all(markers[name].map((marker) => markerExists(project.root, marker)))).some(Boolean);
}

function projectSummary(project: ProjectContext): string {
  const stack = project.facts.map((fact) => fact.value).slice(0, 8).join(", ") || "No supported stack markers detected";
  const boundaries = project.packageBoundaries.length > 0 ? project.packageBoundaries.join(", ") : "single root or no package boundaries detected";
  return `Project: ${project.name}\nDetected stack: ${stack}\nPackage boundaries: ${boundaries}`;
}

function canonicalRules(project: ProjectContext): string {
  return `Read \`.agent-workspace/context/project.md\` before changing code. It separates detected evidence from editable recommendations.
Choose the relevant role in \`.agent-workspace/agents/\` and workflow in \`.agent-workspace/skills/\`.
Use repository commands recorded in project context. Keep changes scoped and report the checks actually run.
Do not treat dependency presence as proof of runtime architecture; inspect affected source before deciding.`;
}

function codexGuide(project: ProjectContext, tool: "OpenAI Codex" | "OpenCode"): string {
  return `${managedHeader}
# ${tool} repository instructions

${projectSummary(project)}

## Working contract

${canonicalRules(project)}

For substantial work, state the selected role and skill, then execute the skill's ordered workflow. Stop when a listed failure condition applies instead of claiming success.
`;
}

function claudeGuide(project: ProjectContext): string {
  return `${managedHeader}
# Claude Code project memory

${projectSummary(project)}

## Before editing

1. Read \`.agent-workspace/context/project.md\`.
2. Select one primary role from \`.agent-workspace/agents/\`.
3. Select the closest skill from \`.agent-workspace/skills/\` and follow its workflow, constraints, validation, and failure conditions.

## Execution

${canonicalRules(project)}

Use focused exploration before broad changes. Summarize assumptions, files changed, commands run, and residual risk when finished.
`;
}

function cursorGuide(project: ProjectContext): string {
  return `---
description: Repository evidence and validated engineering workflows
alwaysApply: true
---

# Cursor project rule

${projectSummary(project)}

${canonicalRules(project)}

Apply the narrowest relevant skill from \`.agent-workspace/skills/\`. Use its validation list as completion criteria and surface its failure conditions explicitly.
`;
}

function copilotGuide(project: ProjectContext): string {
  return `${managedHeader}
# Repository instructions

${projectSummary(project)}

- Consult \`.agent-workspace/context/project.md\` for evidence-backed stack, commands, directories, and conventions.
- Match work to a role under \`.agent-workspace/agents/\` and a workflow under \`.agent-workspace/skills/\`.
- Preserve existing public contracts unless the request explicitly changes them.
- Prefer repository patterns found in affected code over generic framework defaults.
- Run the narrowest relevant checks, then report their exact results.
- Do not claim architectural facts that are only inferred from dependencies.
`;
}

function geminiGuide(project: ProjectContext): string {
  return `${managedHeader}
# Gemini CLI repository context

${projectSummary(project)}

## Context hierarchy

1. Repository source and tests are authoritative.
2. \`.agent-workspace/context/project.md\` records detected evidence and provisional recommendations.
3. \`.agent-workspace/agents/\` defines reviewable engineering responsibilities.
4. \`.agent-workspace/skills/\` defines ordered workflows and validation gates.

${canonicalRules(project)}
`;
}

function createAdapter(name: AdapterName, displayName: string, generateContent: (project: ProjectContext) => string): AgentAdapter {
  return {
    name,
    displayName,
    detect: (project) => detectMarkers(name, project),
    async generate(_workspace: WorkspaceManifest, project: ProjectContext): Promise<GeneratedFile[]> {
      return [{ path: adapterOutputPaths[name], content: generateContent(project), managed: true }];
    },
  };
}

export const adapters: Record<AdapterName, AgentAdapter> = {
  codex: createAdapter("codex", "OpenAI Codex", (project) => codexGuide(project, "OpenAI Codex")),
  claude: createAdapter("claude", "Claude Code", claudeGuide),
  cursor: createAdapter("cursor", "Cursor", cursorGuide),
  copilot: createAdapter("copilot", "GitHub Copilot", copilotGuide),
  gemini: createAdapter("gemini", "Gemini CLI", geminiGuide),
  opencode: createAdapter("opencode", "OpenCode", (project) => codexGuide(project, "OpenCode")),
};

export async function detectAdapters(project: ProjectContext): Promise<AdapterName[]> {
  const entries = Object.entries(adapters) as Array<[AdapterName, AgentAdapter]>;
  const results = await Promise.all(entries.map(async ([name, adapter]) => [name, await adapter.detect(project)] as const));
  return results.filter(([, detected]) => detected).map(([name]) => name);
}

export function uniqueAdapterFiles(files: GeneratedFile[]): GeneratedFile[] {
  const seen = new Set<string>();
  return files.filter((file) => {
    if (seen.has(file.path)) return false;
    seen.add(file.path);
    return true;
  });
}
