import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import YAML from "yaml";
import { adapters, uniqueAdapterFiles } from "./adapters/index.js";
import type { AdapterName, AgentDefinition, GeneratedFile, ProjectContext, SkillDefinition, WorkspaceManifest } from "./schemas.js";

export const GENERATOR_VERSION = "0.2.1";

function yaml(value: unknown): string {
  return YAML.stringify(value, { lineWidth: 100 });
}

function projectMarkdown(project: ProjectContext): string {
  const facts = project.facts.length ? project.facts.map((fact) => `- **${fact.value}** (${fact.category}) — ${fact.confidence}; evidence: \`${fact.source}\``).join("\n") : "- No supported stack markers detected.";
  const commands = project.commands.length ? project.commands.map((item) => `- \`${item.name}\`: \`${item.command}\` — evidence: \`${item.source}\``).join("\n") : "- No package scripts detected.";
  const conventions = project.conventions.length ? project.conventions.map((item) => `- ${item.statement} — ${item.confidence}; evidence: \`${item.source}\``).join("\n") : "- No supported convention files detected.";
  const boundaries = project.packageBoundaries.length ? project.packageBoundaries.map((item) => `\`${item}\``).join(", ") : "None detected";
  return `# Project context\n\nGenerated by agent-workspace. Re-run \`agent-workspace init --force\` to refresh detected data.\n\n## Detected facts\n\n${facts}\n\n## Repository layout\n\n- Source directories: ${project.sourceDirectories.map((item) => `\`${item}\``).join(", ") || "None detected"}\n- Test directories: ${project.testDirectories.map((item) => `\`${item}\``).join(", ") || "None detected"}\n- Package boundaries: ${boundaries}\n\n## Commands\n\n${commands}\n\n## Conventions\n\n${conventions}\n\n## Editable recommendations\n\n${project.recommendations.map((item) => `- ${item}`).join("\n")}\n`;
}

function agentMarkdown(agent: AgentDefinition): string {
  return `# ${agent.name}\n\n${agent.description}\n\n## Responsibilities\n\n${agent.responsibilities.map((item) => `- ${item}`).join("\n")}\n\n## Required context\n\n${agent.requiredContext.map((item) => `- ${item}`).join("\n")}\n\n## Operating principles\n\n${agent.principles.map((item) => `- ${item}`).join("\n")}\n\n## Expected outputs\n\n${agent.outputs.map((item) => `- ${item}`).join("\n")}\n`;
}

export function createManifest(project: ProjectContext, agents: AgentDefinition[], skills: SkillDefinition[], adapterNames: AdapterName[]): WorkspaceManifest {
  return {
    kind: "workspace",
    schemaVersion: "1",
    generator: { name: "agent-workspace", version: GENERATOR_VERSION },
    project: { name: project.name, root: "." },
    agents: agents.map(({ name, version }) => ({ name, version })),
    skills: skills.map(({ name, version }) => ({ name, version })),
    adapters: [...new Set(adapterNames)],
  };
}

export async function buildGeneratedFiles(project: ProjectContext, agentDefs: AgentDefinition[], skillDefs: SkillDefinition[], adapterNames: AdapterName[]): Promise<GeneratedFile[]> {
  const manifest = createManifest(project, agentDefs, skillDefs, adapterNames);
  const canonical: GeneratedFile[] = [
    { path: ".agent-workspace/workspace.yaml", content: yaml(manifest), managed: true },
    { path: ".agent-workspace/context/project.md", content: projectMarkdown(project), managed: true },
    { path: ".agent-workspace/context/project.json", content: `${JSON.stringify({ ...project, root: "." }, null, 2)}\n`, managed: true },
    ...agentDefs.map((agent) => ({ path: `.agent-workspace/agents/${agent.name}.md`, content: agentMarkdown(agent), managed: true })),
    ...skillDefs.map((skill) => ({ path: `.agent-workspace/skills/${skill.name}/skill.yaml`, content: yaml(skill), managed: true })),
  ];
  const projected = (await Promise.all(adapterNames.map((name) => adapters[name].generate(manifest, project)))).flat();
  return [...canonical, ...uniqueAdapterFiles(projected)].sort((a, b) => a.path.localeCompare(b.path));
}

export interface WriteResult { created: string[]; updated: string[]; skipped: string[] }

export async function writeGeneratedFiles(root: string, files: GeneratedFile[], options: { force?: boolean; dryRun?: boolean } = {}): Promise<WriteResult> {
  const result: WriteResult = { created: [], updated: [], skipped: [] };
  for (const file of files) {
    const target = path.resolve(root, file.path);
    const relative = path.relative(path.resolve(root), target);
    if (relative.startsWith("..") || path.isAbsolute(relative)) throw new Error(`Refusing to write outside project: ${file.path}`);
    let current: string | undefined;
    try { current = await readFile(target, "utf8"); } catch { current = undefined; }
    if (current === file.content) continue;
    if (current !== undefined && !options.force) {
      result.skipped.push(file.path);
      continue;
    }
    if (current === undefined) result.created.push(file.path); else result.updated.push(file.path);
    if (!options.dryRun) {
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, file.content, "utf8");
    }
  }
  return result;
}

export async function workspaceExists(root: string): Promise<boolean> {
  try { await access(path.join(root, ".agent-workspace", "workspace.yaml")); return true; } catch { return false; }
}
